In [1]:
#將數據引入
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('maintenance_prediction.csv')
df.head(10)

,date,device,failure,metric1,metric2,metric3,metric4,metric5,metric6,metric7,metric8,metric9
0,1/1/2015,S1F01085,0,215630672,55,0,52,6,407438,0,0,7
1,1/1/2015,S1F0166B,0,61370680,0,3,0,6,403174,0,0,0
2,1/1/2015,S1F01E6Y,0,173295968,0,0,0,12,237394,0,0,0
3,1/1/2015,S1F01JE0,0,79694024,0,0,0,6,410186,0,0,0
4,1/1/2015,S1F01R2B,0,135970480,0,0,0,15,313173,0,0,3
5,1/1/2015,S1F01TD5,0,68837488,0,0,41,6,413535,0,0,1
6,1/1/2015,S1F01XDJ,0,227721632,0,0,0,8,402525,0,0,0
7,1/1/2015,S1F023H2,0,141503600,0,0,1,19,494462,16,16,3
8,1/1/2015,S1F02A0J,0,8217840,0,1,0,14,311869,0,0,0
9,1/1/2015,S1F02DZ2,0,116440096,0,378,9,9,407905,0,0,170

In [2]:
#觀察到mrtric7與metric8相同因此想進行比較
if all(df['metric7']==df['metric8']):
    print("same")
else:
    print("different")

same

In [3]:
#因為metric7與metric8相同，所以刪除
df=df.drop('metric8', axis=1)
df.head(10)

,date,device,failure,metric1,metric2,metric3,metric4,metric5,metric6,metric7,metric9
0,1/1/2015,S1F01085,0,215630672,55,0,52,6,407438,0,7
1,1/1/2015,S1F0166B,0,61370680,0,3,0,6,403174,0,0
2,1/1/2015,S1F01E6Y,0,173295968,0,0,0,12,237394,0,0
3,1/1/2015,S1F01JE0,0,79694024,0,0,0,6,410186,0,0
4,1/1/2015,S1F01R2B,0,135970480,0,0,0,15,313173,0,3
5,1/1/2015,S1F01TD5,0,68837488,0,0,41,6,413535,0,1
6,1/1/2015,S1F01XDJ,0,227721632,0,0,0,8,402525,0,0
7,1/1/2015,S1F023H2,0,141503600,0,0,1,19,494462,16,3
8,1/1/2015,S1F02A0J,0,8217840,0,1,0,14,311869,0,0
9,1/1/2015,S1F02DZ2,0,116440096,0,378,9,9,407905,0,170

In [4]:
#日期與分析無關先刪除
df=df.drop('date', axis=1)
df.head(10)

,device,failure,metric1,metric2,metric3,metric4,metric5,metric6,metric7,metric9
0,S1F01085,0,215630672,55,0,52,6,407438,0,7
1,S1F0166B,0,61370680,0,3,0,6,403174,0,0
2,S1F01E6Y,0,173295968,0,0,0,12,237394,0,0
3,S1F01JE0,0,79694024,0,0,0,6,410186,0,0
4,S1F01R2B,0,135970480,0,0,0,15,313173,0,3
5,S1F01TD5,0,68837488,0,0,41,6,413535,0,1
6,S1F01XDJ,0,227721632,0,0,0,8,402525,0,0
7,S1F023H2,0,141503600,0,0,1,19,494462,16,3
8,S1F02A0J,0,8217840,0,1,0,14,311869,0,0
9,S1F02DZ2,0,116440096,0,378,9,9,407905,0,170

In [5]:
#沒有缺失值
df_nan=df.isna().sum()
df_nan

device     0
failure    0
metric1    0
metric2    0
metric3    0
metric4    0
metric5    0
metric6    0
metric7    0
metric9    0
dtype: int64

In [6]:
#確認壞掉的資料量
fliter = (df["failure"] == 1)
df[fliter]

,device,failure,metric1,metric2,metric3,metric4,metric5,metric6,metric7,metric9
4885,S1F0RRB1,1,48467332,64776,0,841,8,39267,56,1
6879,S1F0CTDN,1,184069720,528,0,4,9,387871,32,3
8823,W1F0PNA5,1,136429411,64784,0,406,30,224801,8,0
11957,W1F13SRV,1,188251248,2040,0,0,6,39345,32,1
12668,W1F1230J,1,220461296,0,0,0,14,325125,0,0
...,...,...,...,...,...,...,...,...,...,...
109927,W1F1CB5E,1,16043296,88,0,0,9,30,0,0
114251,Z1F0MRPJ,1,65654088,0,0,0,9,298592,0,11
122118,S1F0JGJV,1,13739704,0,0,18,8,343760,0,0
122808,Z1F14BGY,1,85259320,0,0,164,8,262932,0,0
124329,W1F0T0B1,1,95073232,0,0,7,9,354861,22,0

 Q1. How many unique device IDs are there in this dataset?

In [8]:
unique_value=df['device'].nunique()
unique_value

1169

 Q2. You are asked to do data analysis. What key findings can you expect to uncover?

In [10]:
#會希望發現metric1-9與failure之間的規律

Q3. You are asked to build a prediction model (with default parameters’ settings). Which kind of machine learning will be used and why? Supervised learning or Unsupervised learning? Regression, classification, or clustering?

In [12]:
#Supervised learning 
#因為是帶有標籤的資料進行學習

In [13]:
# Regression
#我的想法是y_train=failure,x_train=metrics

In [14]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
x = df.iloc[:,2:10].values
y = df.iloc[:,1].values
print(x.shape)
print(y.shape)
print(df.dtypes)

(124494, 8)
(124494,)
device     object
failure     int64
metric1     int64
metric2     int64
metric3     int64
metric4     int64
metric5     int64
metric6     int64
metric7     int64
metric9     int64
dtype: object

In [15]:
clf = LogisticRegression()
clf.fit(x,y)

C:\Users\User\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [16]:
print ('Coefficients: ', clf.coef_)
print ('Intercept: ', clf.intercept_)

Coefficients:  [[-5.14284426e-08  4.18330660e-05 -2.72320564e-04  1.11348021e-03
  -1.21914737e-03 -1.67230084e-05  6.84900357e-04  3.24777590e-05]]
Intercept:  [-0.00011553]

In [17]:
print(clf.predict([[61370680,0,3,0,6,403174,0,0]]))
print(clf.predict([[48467332,64776,0,841,8,39267,56,1]]))

[0]
[1]

In [18]:
print('score:',clf.score(x,y))

score: 0.9991164232814432

In [19]:
#Polynomial regression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 2)

x_poly = poly_reg.fit_transform(x)
reg2 = LinearRegression()

reg2.fit(x_poly, y)

LinearRegression()

In [20]:
print(reg2.predict(poly_reg.fit_transform([[61370680,0,3,0,6,403174,0,0]])))
print(reg2.predict(poly_reg.fit_transform([[48467332,64776,0,841,8,39267,56,1]])))

[0.00051937]
[0.02058938]

In [21]:
print ('Coefficients: ', reg2.coef_)
print ('Intercept: ', reg2.intercept_)

Coefficients:  [-2.87361960e-19  3.36804713e-12 -5.48149612e-15  6.68387100e-16
  2.14243965e-16 -5.54760746e-18  1.49331081e-13  1.04264716e-15
 -8.99087298e-17 -8.28990414e-21 -1.79090255e-15 -4.18446460e-15
  2.42345423e-13  7.38351305e-14 -9.78136222e-18  2.96147629e-12
  4.28754850e-15 -8.75826973e-13 -1.16806404e-12  8.28319942e-12
 -3.91923685e-13  2.41518366e-12  1.96161609e-11 -1.28116505e-12
 -5.60629906e-11 -1.33999390e-12  2.99973546e-14  1.75560990e-12
  1.42941621e-15 -2.10855633e-11  1.26380096e-13  1.75859697e-15
  8.88568026e-11  3.02469822e-14 -5.18590006e-13  2.45169317e-16
  1.92702721e-12  8.74910438e-15  2.12182099e-14  9.30083116e-16
  8.24700895e-10 -1.31623641e-12 -2.79868796e-13  8.13196906e-13
  4.80051949e-12]
Intercept:  0.00040147235607766567

In [22]:
print('score:',reg2.score(x_poly,y))

score: 0.02541832214801687

In [23]:
# SVC(適用高維度獨立數據)
from sklearn import svm
clf = svm.SVC()
clf.fit(x,y)

SVC()

In [24]:
print(clf.predict([[61370680,0,3,0,6,403174,0,0]]))
print(clf.predict([[48467332,64776,0,841,8,39267,56,1]]))

[0]
[0]

In [25]:
print('score:',clf.score(x,y))

score: 0.9991485533439363

In [26]:
# K-NN
from sklearn import neighbors
clf = neighbors.KNeighborsClassifier()
clf.fit(x,y)

KNeighborsClassifier()

In [27]:
print(clf.predict([[61370680,0,3,0,6,403174,0,0]]))
print(clf.predict([[48467332,64776,0,841,8,39267,56,1]]))

[0]
[0]

In [28]:
print('score:',clf.score(x,y))

score: 0.9991485533439363

In [29]:
# Gaussian Naive bayes
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(x,y)

GaussianNB()

In [30]:
print(clf.predict([[61370680,0,3,0,6,403174,0,0]]))
print(clf.predict([[48467332,64776,0,841,8,39267,56,1]]))

[0]
[1]

In [31]:
print('score:',clf.score(x,y))

score: 0.9974054974536926

In [32]:
# Multinomail Naive bayes
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(x,y)

MultinomialNB()

In [33]:
print(clf.predict([[61370680,0,3,0,6,403174,0,0]]))
print(clf.predict([[48467332,64776,0,841,8,39267,56,1]]))

[0]
[1]

In [34]:
print('score:',clf.score(x,y))

score: 0.724717657075843

In [35]:
#Decision tree regression
from sklearn.tree import DecisionTreeRegressor
clf=DecisionTreeRegressor()
clf.fit(x,y)

DecisionTreeRegressor()

In [36]:
print(clf.predict([[61370680,0,3,0,6,403174,0,0]]))
print(clf.predict([[48467332,64776,0,841,8,39267,56,1]]))

[0.]
[1.]

In [37]:
print('score:',clf.score(x,y))

score: 0.9952789991875695

In [38]:
# Decision Tree
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf.fit(x,y)

DecisionTreeClassifier()

In [39]:
print(clf.predict([[61370680,0,3,0,6,403174,0,0]]))
print(clf.predict([[48467332,64776,0,841,8,39267,56,1]]))

[0]
[1]

In [40]:
print('score:',clf.score(x,y))

score: 0.9999919674843768

In [41]:
#Random forest
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier()
clf.fit(x,y)

RandomForestClassifier()

In [42]:
print(clf.predict([[61370680,0,3,0,6,403174,0,0]]))
print(clf.predict([[48467332,64776,0,841,8,39267,56,1]]))

[0]
[1]

In [43]:
print('score:',clf.score(x,y))

score: 0.9999919674843768

In [44]:
# XGBoost
from xgboost.sklearn import XGBClassifier
clf = XGBClassifier()
clf.fit(x,y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [45]:
print(clf.predict([[61370680,0,3,0,6,403174,0,0]]))
print(clf.predict([[48467332,64776,0,841,8,39267,56,1]]))

[0]
[1]

In [46]:
print('score:',clf.score(x,y))

score: 0.9996546018282005

Q4. There are two data from two devices, please predict the corresponding failure values.

In [48]:
Test1=[127175526,4109.434,3.90566,54.63208,15.46226,258303.5,30.62264,23.08491]
Test2=[4527376,0,0,0,3,24,0,0]

1.Decision Tree

In [50]:
# Decision Tree
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf.fit(x,y)
print(clf.predict([[127175526,4109.434,3.90566,54.63208,15.46226,258303.5,30.62264,23.08491]]))
print(clf.predict([[4527376,0,0,0,3,24,0,0]]))

[0]
[0]

Random Forest

In [52]:
#Random forest
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier()
clf.fit(x,y)
print(clf.predict([[127175526,4109.434,3.90566,54.63208,15.46226,258303.5,30.62264,23.08491]]))
print(clf.predict([[4527376,0,0,0,3,24,0,0]]))

[0]
[0]

XGBoost

In [54]:
# XGBoost
from xgboost.sklearn import XGBClassifier
clf = XGBClassifier()
clf.fit(x,y)
print(clf.predict([[127175526,4109.434,3.90566,54.63208,15.46226,258303.5,30.62264,23.08491]]))
print(clf.predict([[4527376,0,0,0,3,24,0,0]]))

[0]
[0]